### PR TITLE
Add default file extension handling.

### PR DESCRIPTION
**Pull request by aliebuck**
I've also done a bit of a clean up to the plugin, hence the crazy diff.

### CODE REVIEW

**Comment by webpro** [comment]
Thanks for the PR. Could you please explain what the changes actually do or fix?

**Comment by aliebuck** [comment]
It adds the ability to have a default file extension when loading modules. The default I've set is `.mustache`, so if you `require('template')` then you'll get `template.mustache`. Otherwise if you `require('template.html')` then you'll get `template.html`.

The default extension can be configured too:

``` js
requirejs.config({
  hgn: {
    extension: 'hjs'
  }
});
```

The other changes I've made are using `hasOwnProperty` rather than `in`, and moving the `read` and `write` functions into an object to return.

**Comment by webpro** [comment]
OK thanks @jacobbuck! Let me know if you'd like this to be tagged for Bower and/or released in npm.

**Comment by aliebuck** [comment]
Cool thanks. Hmm, might be worth bumping up the version number and publishing on bower/npm.

**Comment by webpro** [comment]
Done. But publishing to npm doesn't make a lot of sense since it's AMD (i.e. not CommonJS compatible).

**Pull request merged**
